services:
  - type: web
    name: go3d-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: NOTIFY_BOT_TOKEN
        sync: false
      - key: SITE_URL
        value: https://3-days.ru
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
